// Importing Scanner and Random for use in the later methods.
import java.util.Scanner;
import java.util.Random;

public class BookingSystem {
    
    private static String[] typeOfRooms = {"double","queen","king"};
    private static Random r = new Random(123);
    
    //returns a random String from the above array. 
    private static String getRandomType(){
        int index = r.nextInt(typeOfRooms.length);
        return typeOfRooms[index];
    }
    //returns a random number of rooms between 5 and 50.
    private static int getRandomNumberOfRooms(){
        return r.nextInt(50)+1;
    }
    //End of code. 
    
    public static void main(String[] args){
      String hotelName;
      Room[] roomList;
      Hotel myHotel;
      Reservation[] reservationList;
      int userInput;
      String userName, desiredRoomType;
      // Using scanner to create the boxes for the entering of the hotel name.
      Scanner read = new Scanner(System.in);
      System.out.print("Please enter the name of the hotel you'd like to book ");
      hotelName = read.nextLine();
      int numOfRooms;
      numOfRooms = getRandomNumberOfRooms();
      // Creating an array of a size that matches the amount of rooms generated by the random operation above.
      roomList = new Room[numOfRooms];
      reservationList = new Reservation[numOfRooms];
      for (int i = 0; i < numOfRooms; i++) {
      // Calling the getRandomType method to create the room objects for use in the roomList array.
        roomList[i] = new Room(getRandomType());
      }
      myHotel = new Hotel (hotelName, roomList);
      // Writing down all the options in the menu. Using a while loop so that they keep appearing.
      while(true) {
      System.out.println("Welcome to " + hotelName + ". Chose one of the following options: ");
      System.out.println("1) Make a reservation");
      System.out.println("2) Cancel a reservation");
      System.out.println("3) See an invoice");
      System.out.println("4) See hotel info");
      System.out.println("5) Exit the Booking System");
      userInput = read.nextInt();
      // Checking that the userInput is valid so that the programme can continue.
      if(userInput <= 5 && userInput >= 1) {
        // Writing down all the code for "Make a reservation".
        if(userInput == 1) {
        userName = read.nextLine();
        System.out.print("Please enter your name: ");
        userName = read.nextLine();
        System.out.print("What type of room would you like to reserve? ");
        desiredRoomType =  read.nextLine();
        myHotel.createReservation(userName, desiredRoomType);
        }
        // Writing down all the code for "Cancel a reservation".
        if(userInput == 2) {
        userName = read.nextLine();
        System.out.print("Please enter the name you used to make the reservation ");
        userName = read.nextLine();
        System.out.print("What type of room did you reserve? ");
        desiredRoomType = read.nextLine();
        myHotel.cancelReservation(userName, desiredRoomType);
        }
        // Writing down all the code for "See an invoice".
        if(userInput == 3) {
        userName = read.nextLine();
        System.out.print("Please enter your name: ");
        userName = read.nextLine();
        myHotel.printInvoice(userName);
        }
        // Writing down all the code for "See hotel info".
        if(userInput == 4) {
        System.out.println("Here is the hotel info ");
        System.out.println(myHotel.toString());
      }
        // Writing down all the code for "Exit the Booking System".
        if(userInput == 5) {
        System.out.println("It was a pleasure doing business with you! ");
        break;
        }
      }
      // If an appropriate intger has not been input, an error message is displayed.
      else {
        System.out.println("Error: You have not inputted a valid integer between 1 and 5.");
      }
     }
    }
}